-- Idempotent ingest for daily_task.tbl_scwts_sarujanan (dedup key: project_code, activity_id)
CREATE TABLE IF NOT EXISTS daily_task.tbl_scwts_sarujanan (
  project_code text NOT NULL,
  activity_id text NOT NULL,
  activity_date date NOT NULL DEFAULT CURRENT_DATE,
  developer text NOT NULL DEFAULT 'sarujanan',
  project_name text,
  requirement_id text,
  deliverable_id text,
  activity_type text NOT NULL,
  activity_title text NOT NULL,
  activity_summary text NOT NULL,
  systems_touched text,
  files_touched text,
  evidence_refs text,
  reusable_asset_created boolean NOT NULL DEFAULT false,
  reusable_pattern text,
  validation_rule text,
  gap_or_risk text,
  next_action text,
  status text NOT NULL DEFAULT 'completed',
  priority text NOT NULL DEFAULT 'medium',
  llm_queryable boolean NOT NULL DEFAULT true,
  company_knowledge_candidate boolean NOT NULL DEFAULT false,
  memory_tags text,
  source_skill_file text,
  source_type text NOT NULL DEFAULT 'skill_file',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tbl_scwts_sarujanan_pkey PRIMARY KEY (project_code, activity_id)
);

INSERT INTO daily_task.tbl_scwts_sarujanan (
  project_code, activity_id, activity_date, developer, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type
) VALUES
('scwts','D01-A01','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','architecture','Redesign dashboard data architecture to raw-data-first','Replaced the previous aggregated-KPI dashboard model with a raw-data-first architecture: PostgreSQL -> SQL export of complete datasets -> single embedded data.js -> offline HTML dashboard -> JavaScript filtering -> cards, charts and tables. This removes any dependency on backend API calls while the dashboard is in use.','postgresql, javascript, html-dashboard','dashboard/data.js; dashboard/script.js; dashboard/index.html','SKILL 1 System State; SKILL 2 What Changed Today; SKILL 7 Decisions; architecture PostgreSQL->SQL Export->data.js->Offline Dashboard->JS filtering',TRUE,'Export complete transactional datasets (never aggregates), embed once, then compute and filter entirely client-side.','Dashboard KPIs must derive from raw datasets, not summary values (VR01).','If only KPI totals are exported, historical filtering and custom reporting periods become impossible.','Reconnect data.js to a refreshable PostgreSQL export pipeline; current build is an embedded snapshot.','completed','high',TRUE,TRUE,'scwts,dashboard,architecture,raw-data-first,offline,data.js,client-side','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A02','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','data-export','Create SQL export queries returning complete datasets','Authored one SQL export file per dataset that returns complete raw rows instead of aggregated totals, covering the operational lineage: components, component-to-combo mapping, combo SKUs, marketplace listings, orders, sales, traffic and returns, windowed from 2026-01-01. Each query documents purpose, source tables, joins, filters and output.','postgresql','sql/components.sql; sql/combos.sql; sql/component_combo_mapping.sql; sql/listings.sql; sql/orders.sql; sql/traffic.sql; sql/returns.sql','SKILL 2 (dataset list); SKILL 5 VR04; evidence_location dashboard/sql/',TRUE,'One SQL file per dataset returning raw rows so any reporting period can be recomputed without new SQL.','SQL export files must return complete records instead of aggregated totals (VR04).','Raw traffic volume (millions of rows) is too large to embed offline, so traffic is aggregated per listing.','Parameterize each export with :start_date/:end_date for scheduled refreshes.','completed','high',TRUE,TRUE,'scwts,sql,export,components,combos,listings,orders,returns,traffic,raw-rows','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A03','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','implementation','Consolidate exported datasets into a single embedded data.js','Combined the exported datasets into one offline data.js that the dashboard loads with no backend or API calls. Rows are stored as compact arrays with a column-schema manifest in meta so the front end can address fields by index.','javascript, html-dashboard','dashboard/data.js','SKILL 2 What Changed Today; SKILL 7 Decisions; evidence_location dashboard/data.js',TRUE,'Embed complete datasets as arrays-of-arrays plus a schema manifest for compact offline storage.','Dashboard values must never rely on hardcoded summary statistics (VR03).','Embedded data is a point-in-time snapshot; refreshing requires re-running the SQL exports.','Add a regenerate script that rebuilds data.js from the SQL exports.','completed','high',TRUE,TRUE,'scwts,data.js,embedded,offline,dataset,snapshot','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A04','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','feature','Implement dashboard Date Range Filter with client-side recompute','Added a header From/To date range filter defaulting to 2026-01-01 through the current date. Changing the range recalculates every dashboard section (KPI cards, charts, tables, journey funnel, marketplace status, supplier statistics, sales and returns summaries) entirely in JavaScript from the embedded datasets, issuing no further PostgreSQL queries.','javascript, html-dashboard','dashboard/index.html; dashboard/script.js; dashboard/style.css','SKILL 2 (Date Range Filter, default 2026-01-01->Current Date); SKILL 5 VR02',TRUE,'A single date-range control drives one compute() function that every view reads from.','Changing the date filter must update KPI cards, charts, tables, journey funnel, marketplace, supplier, sales and returns (VR02).','None identified.','Persist the selected range in the URL or localStorage across reloads.','completed','high',TRUE,TRUE,'scwts,date-filter,client-side,recompute,dashboard','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A05','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','implementation','Compute all KPIs, charts and tables dynamically in JavaScript','All cards, charts, journey views, marketplace summaries and tables are computed at render time in JavaScript from the embedded raw datasets for the selected date range, following the lineage New Component -> Combo -> Marketplace Listing -> Orders -> Sales -> Returns. No aggregated values are stored in the dashboard.','javascript','dashboard/script.js','SKILL 2 What Changed Today; SKILL 3 operational relationship; SKILL 5 VR01',FALSE,'Derive every KPI from raw rows at render time rather than storing precomputed totals.','Every dashboard KPI must be calculated from raw datasets stored inside data.js (VR01).','None identified.','Add automated checks comparing JS-computed KPIs against a PostgreSQL recompute.','completed','medium',TRUE,FALSE,'scwts,kpi,javascript,dynamic,lineage,compute','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A06','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','validation','Add dashboard validation rules VR01 to VR04','Documented four validation rules governing the dashboard: VR01 every KPI computed from raw data.js datasets; VR02 a date-filter change must update all sections; VR03 no hardcoded summary statistics; VR04 SQL exports must return complete records, not aggregates. Captured in the validation report.','postgresql, javascript','validation/data_validation_report.md','SKILL 5 Validation Rule Added or Changed (VR01-VR04); evidence_location dashboard/validation/',TRUE,'Validation rules asserting raw-data provenance and full filter coverage for reporting dashboards.','VR01 raw-data KPIs; VR02 filter updates all sections; VR03 no hardcoded summaries; VR04 complete-record exports.','None identified.','Automate the VR01-VR04 checks in CI against the exported data.','completed','high',TRUE,TRUE,'scwts,validation,rules,data-provenance,quality','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A07','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','documentation','Extract reusable company pattern for offline reporting dashboards','Recorded a reusable company pattern for standalone HTML dashboards that need historical reporting: PostgreSQL -> export complete datasets -> embed data.js -> client-side filtering -> dynamic KPI calculation, with layered separation of extraction, storage, presentation, filtering and visualization. It is reusable across future inventory, finance, logistics and marketplace dashboards.','documentation','2026-07-21__sarujanan__scwts__REQ-01-D01.md','SKILL 8 Company Knowledge Extract',TRUE,'PostgreSQL->export complete datasets->embed data.js->client-side filter->dynamic KPIs; separate extraction/storage/presentation/filtering/visualization.','Avoid exporting aggregated statistics; always export reusable transactional datasets.','None identified.','Apply this pattern to the next reporting dashboard build.','handoff_ready','medium',TRUE,TRUE,'scwts,company-knowledge,reusable-pattern,dashboard,architecture','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file'),
('scwts','D01-A08','2026-07-21','sarujanan','Supplier-to-Customer Workflow Tracking System','REQ-01','D01','gap-analysis','Identify data-completeness and metric-consistency gaps','Logged gaps found during implementation: earlier SQL exports produced summary statistics rather than complete datasets; Orders, Sales and Returns were validated using transaction dates only; some dashboard sections mixed all-time metrics with reporting-period metrics causing inconsistent interpretation; and the embedded dataset must contain every record from 2026-01-01 onwards instead of pre-calculated totals.','postgresql, javascript','sql/; dashboard/data.js','SKILL 4 Gap Found; SKILL 6 Failure Mode or Edge Case',FALSE,NULL,'The embedded dataset should contain every record from 2026-01-01 instead of pre-calculated totals.','Summary-only exports prevent historical recalculation; mixed all-time vs period metrics; incomplete raw data makes orders, sales and returns inconsistent.','Ensure all exports return complete records and unify every section to the selected reporting period.','gap_identified','high',TRUE,FALSE,'scwts,gap,data-completeness,metric-consistency,risk','2026-07-21__sarujanan__scwts__REQ-01-D01.md','skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET
  activity_date=EXCLUDED.activity_date,
  developer=EXCLUDED.developer,
  project_name=EXCLUDED.project_name,
  requirement_id=EXCLUDED.requirement_id,
  deliverable_id=EXCLUDED.deliverable_id,
  activity_type=EXCLUDED.activity_type,
  activity_title=EXCLUDED.activity_title,
  activity_summary=EXCLUDED.activity_summary,
  systems_touched=EXCLUDED.systems_touched,
  files_touched=EXCLUDED.files_touched,
  evidence_refs=EXCLUDED.evidence_refs,
  reusable_asset_created=EXCLUDED.reusable_asset_created,
  reusable_pattern=EXCLUDED.reusable_pattern,
  validation_rule=EXCLUDED.validation_rule,
  gap_or_risk=EXCLUDED.gap_or_risk,
  next_action=EXCLUDED.next_action,
  status=EXCLUDED.status,
  priority=EXCLUDED.priority,
  llm_queryable=EXCLUDED.llm_queryable,
  company_knowledge_candidate=EXCLUDED.company_knowledge_candidate,
  memory_tags=EXCLUDED.memory_tags,
  source_skill_file=EXCLUDED.source_skill_file,
  source_type=EXCLUDED.source_type,
  updated_at=now();
