-- SCWTS 2026-07-31 REQ-02-D01 - idempotent ingest (safe to re-run)

CREATE SCHEMA IF NOT EXISTS daily_task;

CREATE TABLE IF NOT EXISTS daily_task.tbl_scwts_sarujanan (
  activity_id text NOT NULL, activity_date date, developer text DEFAULT 'sarujanan',
  project_code text NOT NULL, project_name text, requirement_id text, deliverable_id text,
  activity_type text, activity_title text, activity_summary text, systems_touched text,
  files_touched text, evidence_refs text, reusable_asset_created boolean, reusable_pattern text,
  validation_rule text, gap_or_risk text, next_action text, status text DEFAULT 'completed',
  priority text DEFAULT 'medium', llm_queryable boolean, company_knowledge_candidate boolean,
  memory_tags text, source_skill_file text, source_type text DEFAULT 'skill_file',
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (project_code, activity_id));

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A01', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'implementation', 'Parse the manager''s container workbook into a Container to Component SKU map', 'Built a standard-library .xlsx parser (an xlsx is a zip of XML; pip install openpyxl is blocked by PEP 668 in this environment). Header row and SKU/Image columns are located by NAME not position so the parser survives column reordering. Result: 6 containers, 210 sheet rows, 209 distinct SKUs; LSGLULSG legitimately appears in both Container 12 and 13; Container 17 tab is empty.', 'Google Sheet export; local filesystem', 'dashboard-v3-sql/read_sheet.py; dashboard-v3-sql/sheet_containers.json', '6 containers / 210 rows / 209 distinct SKUs parsed', TRUE, 'stdlib xlsx parser keyed on header NAME rather than column position', 'Every sheet SKU must appear in the dashboard: 209/209', 'Container 17 tab is present but empty - needs manager confirmation', 'Confirm with Varmen whether Container 17 should contain SKUs', 'completed', 'high', TRUE, TRUE, 'google-sheet,xlsx,container-mapping,stdlib-parser', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A02', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'investigation', 'Discover the source database being dismantled mid-session', 'While validating, public.inv_products, public.inv_product_combo, public.amazon_returns and all six supplier.* tables dropped to 0 rows, and public.ebay_returns and public.shopify_returns were dropped outright. listing_data, order_transaction, traffic_data and ppc_performance survived. Dashboard V2''s hard gates caught this and correctly refused to publish, so neither the live dashboard nor the hub copy was overwritten.', 'PostgreSQL order_management_copy', 'logs/automation_v2.log', '4 tables emptied to 0 rows; 2 tables dropped; V2 build exited 1 without publishing', FALSE, 'Hard validation gates that block publish are what turn a data outage into a safe no-op', 'Source-availability probe runs before any dependent query and records row counts', 'Dashboard V2''s scheduled 11:00 run will keep failing until it is repointed at the ledsone database', 'Repoint Dashboard V2 at ledsone or accept a red cron', 'completed', 'high', TRUE, TRUE, 'data-migration,source-outage,validation-gate,incident', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A03', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'investigation', 'Answer the container received-date question definitively', 'Searched every schema of the new ledsone database for any date column meaning arrival or receipt using the pattern arriv|receiv|inbound|delivere|landed|grn|eta|ata|clear. Only two hits, both unrelated (returns delivery date and eBay message receipt). Dumped all 41 container rows across containers and final_containers: the only dates are created_at and updated_at. status_arrived is a boolean with no accompanying date, so the system records that goods arrived but never when.', 'PostgreSQL ledsone (LEDs One MCP)', 'dashboard-v3-sql/V3_DATA_SOURCE_SPEC.md', '41 container rows inspected; 0 carry an arrival date', FALSE, 'Prove a field''s absence by scanning information_schema across all schemas, not by checking the obvious table', 'No receipt date may be inferred from updated_at because it moves on never-arrived rows', 'There is no auditable container receipt date anywhere in the system', 'Request an arrived_date column on suppliers.final_containers at source', 'completed', 'high', TRUE, TRUE, 'container,received-date,data-gap,schema-audit', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A04', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'implementation', 'Build Dashboard V3 as an independent container-first deliverable', 'Created Dashboard V3 in new dashboard-v3 and dashboard-v3-sql folders, leaving Dashboard V2 completely untouched (MD5 unchanged). Scope is driven by the Google Sheet rather than the database, which is the core difference from V2. Row grain is one row per container, product and marketplace, with the product being the combo where one exists and the component otherwise.', 'PostgreSQL order_management_copy; local filesystem', 'dashboard-v3-sql/build_v3.py; dashboard-v3-sql/payload_v3.json; dashboard-v3/index.html', '781 rows across 6 containers; 209 components; 295 combos', TRUE, 'Sheet-driven scope: a business-owned spreadsheet defines what is in scope, the database supplies the detail', 'No duplicate container-product-marketplace rows; fan-out gate carried over from V2', 'Component to Combo mapping is inferred from SKU naming because inv_product_combo is empty', 'Get inv_product_combo migrated so the mapping stops being an inference', 'completed', 'high', TRUE, TRUE, 'dashboard-v3,container-view,sheet-driven-scope', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A05', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'bugfix', 'Swap the inv_products source to LEDs One inventory.products', 'public.inv_products is a stale dead copy (0 rows) on the project database, so per instruction the only source swapped was inv_products, which now comes from the LEDs One MCP inventory.products. No direct credentials exist for ledsone so the master was extracted in three exact-SKU chunks into a local cache. A regex scan across all 43,949 products timed out over MCP whereas exact-SKU ANY(ARRAY[...]) lookups return instantly.', 'PostgreSQL ledsone (LEDs One MCP); PostgreSQL order_management_copy', 'dashboard-v3-sql/ledsone_products.json; dashboard-v3-sql/build_v3.py', '420 products cached; Component Created Dates 775/776 populated', TRUE, 'Chunked exact-SKU extraction over MCP; avoid regex scans that time out', 'Component and Combo Created Dates must come from LEDs One, never from the stale copy', '84 combo SKUs (mostly locale variants) and 1 component (PCRMFF) are absent from inventory.products', 'Ask whether the missing locale-variant SKUs should exist as products', 'completed', 'high', TRUE, TRUE, 'ledsone,inv-products,source-of-truth,mcp-extraction', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A06', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'enhancement', 'Apply the requested V3 UI changes only', 'Removed the Supplier and Received Date columns leaving 18, and added a Container tab list with live per-container counts plus an All Containers tab. The grouped product layout, filters, search, sorting, pagination, CSV export, theme and responsive behaviour were kept identical to Dashboard V2.', 'local filesystem', 'dashboard-v3-sql/make_html_v3.py; dashboard-v3/index.html', '18 columns; 6 container tabs; rows per container 83/325/165/91/2/110', FALSE, 'Reuse the prior version''s style block verbatim so a new dashboard inherits the whole design system', 'Supplier and Received Date must not appear in the V3 column set', 'None', 'Monitor whether users want container filtering combined with marketplace filtering', 'completed', 'medium', TRUE, TRUE, 'dashboard-v3,ui,container-tabs', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A07', DATE '2026-07-31', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'enhancement', 'Add Dashboard V2''s detail drawer to V3', 'Ported V2''s click-through side drawer with identical markup, CSS, open and close behaviour, Escape handling, backdrop click and the reflow fix that prevents an invisible overlay swallowing clicks. V2''s Supply chain card was replaced by a Container card because Supplier and Received Date no longer exist in V3. The multi-component stack behaviour is preserved: values collapse when all components agree and list separately when they differ.', 'local filesystem', 'dashboard-v3-sql/make_html_v3.py; dashboard-v3/index.html', 'All 781 rows are drawer-addressable via a RENDERED index rebuilt each render', FALSE, 'Rebuild the row-to-record index on every render so drawers stay correct across tabs, filters and paging', 'Drawer index must be rebuilt on every render, not cached', 'None', 'None', 'completed', 'medium', TRUE, TRUE, 'dashboard-v3,drawer,ui-parity', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A08', DATE '2026-08-03', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'bugfix', 'Fix Component Images being taken from the marketplace instead of the Google Sheet', 'Varmen reported LHPVHRE27WH showing the wrong image. Root cause was a one-word bug: the image map was populated from listing_data first and the sheet image was then applied with dict.setdefault, which is a no-op when the key already exists. Every SKU that had a marketplace listing therefore kept the marketplace photo and the sheet image was silently discarded, the exact opposite of the code comment. Fixed by assigning directly so the sheet always wins, leaving listing_data as fallback only.', 'Google Sheet; PostgreSQL order_management_copy', 'dashboard-v3-sql/build_v3.py; dashboard-v3/index.html', '95 SKUs corrected; 207/209 components now render the sheet image; LHPVHRE27WH now Productimages/23713.jpeg', FALSE, 'setdefault silently loses a precedence override - assign directly when the later source must win', 'Component Image must equal the Google Sheet Image Link for every SKU that has one', '2 components (PCRMFF, SPPGUK3PGD) have a blank Image Link in the sheet', 'Ask Varmen to fill the 2 missing Image Link cells', 'completed', 'high', TRUE, TRUE, 'bugfix,image-mapping,google-sheet,setdefault-trap', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A09', DATE '2026-08-03', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'validation', 'Validate all 18 dashboard fields independently against their sources', 'Wrote a standalone validator that re-derives every field from its original source and diffs it against the published payload, rather than trusting the builder''s own output. Covered Component SKU, Component Image, Component Created Date, Combo SKU, Combo Image, Combo Created Date, Listing Status, Marketplace, Listed Date, Impressions, Clicks, Orders, Units Sold, Revenue, Total Returns, Return Rate, Top Reason and Average Feedback. Result: 0 mismatches across 781 rows and 794 component cells.', 'PostgreSQL order_management_copy; Google Sheet; LEDs One cache', 'dashboard-v3-sql/validate_v3.py; dashboard-v3-sql/validation_v3.json', '18 fields checked; 0 mismatches; 781 rows; 209 components', TRUE, 'Independent re-derivation validator: never validate a pipeline using the pipeline''s own output', 'Every displayed field must equal an independent re-derivation from its source', 'Top Reason and Average Feedback remain unavailable - no reason data and no review table on this database', 'Decide whether V3 may read returns and feedback from LEDs One to close these two fields', 'completed', 'high', TRUE, TRUE, 'validation,independent-rederivation,zero-mismatch', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A10', DATE '2026-08-03', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-02', 'D01', 'deployment', 'Publish V3 to the Varman AIOS hub and rename the page slug', 'Published Dashboard V3 to the hub, then renamed the slug from supplier-to-customer-workflow-tracking-v3 to container-to-customer-workflow-tracking. Because the upsert key is member_name plus page_slug the hub has no rename operation, so the new slug was published and MD5-verified first and only then was the old row deleted, meaning the page was never unavailable. Republished after the image fix; the hub copy was verified byte-for-byte and confirmed to carry the corrected image URL.', 'varman_aios.hub_pages; local filesystem', 'dashboard-v2-update/push_to_hub.js; dashboard-v3/index.html', 'hub id 125 container-to-customer-workflow-tracking; MD5 99743871573da1746be779e17a76c7da matches local', FALSE, 'Rename a hub page by publish-verify-then-delete so the page is never offline', 'Hub html_content MD5 must equal the local file MD5 after every publish', 'None', 'None', 'completed', 'high', TRUE, TRUE, 'deployment,aios-hub,slug-rename,md5-verify', '2026-07-31__sarujanan__scwts__REQ-02-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

-- confirm
SELECT activity_id, activity_date, activity_type, priority, activity_title
FROM daily_task.tbl_scwts_sarujanan
WHERE project_code='scwts' AND deliverable_id='D01' AND requirement_id='REQ-02'
ORDER BY activity_id;
SELECT count(*) AS scwts_total FROM daily_task.tbl_scwts_sarujanan WHERE project_code='scwts';
