-- SCWTS 2026-09-15 REQ-03-D01 - idempotent ingest (safe to re-run)

CREATE SCHEMA IF NOT EXISTS daily_task;

CREATE TABLE IF NOT EXISTS daily_task.tbl_scwts_sarujanan (
  activity_id text NOT NULL, activity_date date, developer text DEFAULT 'sarujanan',
  project_code text NOT NULL, project_name text, requirement_id text, deliverable_id text,
  activity_type text, activity_title text, activity_summary text, systems_touched text,
  files_touched text, evidence_refs text, reusable_asset_created boolean, reusable_pattern text,
  validation_rule text, gap_or_risk text, next_action text, status text DEFAULT 'completed',
  priority text DEFAULT 'medium', llm_queryable boolean, company_knowledge_candidate boolean,
  memory_tags text, source_skill_file text, source_type text DEFAULT 'skill_file',
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (project_code, activity_id));

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A01', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'validation', 'Validate the LEDs One migration and keep the old database for two values only', 'Confirmed Dashboard V2 runs on LEDSone through the pg_temp source layer with the business SQL unchanged. The old order_management_copy is read for exactly two things: the isdeleted flag and the 10 order sources LEDSone does not carry. Google Ads product_performance holds superseded duplicate ids, so the latest version per id is used. Two fallback rules added during the migration (catalogue image, PO-header container) were reverted on instruction because they were new business rules.', 'PostgreSQL ledsone; PostgreSQL order_management_copy', 'dashboard-v2-sql/v2_sources.py; dashboard-v2-sql/build_v2.py', 'combo links 366/366; order lines 8,855/8,855; Google Ads 802,585/802,585 exact', TRUE, 'Migrate a database by recreating the OLD table shapes as temp views, so business SQL never changes', 'Every migrated field compared old-vs-new before use', 'Old DB still required for isdeleted and 10 order sources', 'Ask the DB owner to carry isdeleted and the missing order sources into LEDSone', 'completed', 'high', TRUE, TRUE, 'migration,ledsone,temp-views,source-layer', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A02', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'implementation', 'Fix the product images, the Record ID and the duplicated combo rows', 'Images now come from the database catalogue (inventory.product_images, then product_media main-image) when the supplier and listing photos are blank, clearing all 81 empty image cells. The Record ID is written once per product with a rowspan instead of repeating on every marketplace row, and is numbered in display order. The Combos tab no longer repeats component-only rows.', 'PostgreSQL ledsone', 'dashboard-v2-sql/build_v2.py; dashboard-v2-sql/make_html.py', '81 blank images -> 0; one Record ID per product group', FALSE, 'Fill a blank display field from the catalogue only after the primary sources are exhausted', 'No product may appear twice within one tab', 'None', 'None', 'completed', 'medium', TRUE, TRUE, 'images,record-id,deduplication', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A03', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'implementation', 'Order rows by data completeness and hide the three combo-only columns', 'Default display order is container plus received date first, then container only, then neither, so the most complete rows lead. On the Components tab the three combo columns (Combo SKU, Image, Created) are hidden because they are always blank there. Sorting, filters and paging were untouched.', 'local filesystem', 'dashboard-v2-sql/make_html.py', 'display-priority bands 1/2/3 applied; column set unchanged on the Combos tab', FALSE, 'Order by completeness only in the default view, so an explicit user sort always wins', 'Data values must not change when only the order changes', 'None', 'None', 'completed', 'medium', TRUE, TRUE, 'ui,ordering,columns', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A04', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'deployment', 'Publish the validated build to the Varman AIOS hub', 'The 11:00 cron build passed its gates, so it was pushed to varman_aios.hub_pages as member sarujanan and verified by MD5 against the local file. A manual full rebuild had failed on the LEDSone role connection limit, so the already-validated artefact was published rather than rebuilding under a failing connection. The publish also needed the pg module reinstalled in dashboard-v2-update after a dangling symlink.', 'varman_aios.hub_pages; local filesystem', 'dashboard-v2-update/push_to_hub.js; dashboard-v2/index.html', 'hub id 65 updated 2026-09-15 11:15:44; MD5 matches local', FALSE, 'Publish the artefact that passed, never a rebuild made under a degraded connection', 'Hub html_content MD5 must equal the local file MD5 after every publish', 'LEDSone tech_user hits too many connections for role', 'Add a retry loop to the refresh script', 'completed', 'high', TRUE, TRUE, 'deployment,aios-hub,md5-verify,connection-limit', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A05', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'investigation', 'Trace where container and received date are lost, across three systems', 'Compared the admin UK Supply List, the Inventory team dashboard and LEDSone SKU by SKU over 13 sample groups (IMACCW, LHXSHE27BM, SU1318 group, CRSP cables, CRSFX120, CBSF95, MBWHBSL, LSCY2902, LSGLST, LSMS3202). Proved that final_containers.status=''completed'' is set at DISPATCH, not receipt: UK Container 8th 2026 is completed with an invoice ship-by of 9 Sep, 0 of 157 lines arrived and zero stock. Also found SKU re-coding (IMACCW receipt recorded under IMAC7714CW), containers never assigned on shipped POs, and warehouse id 33 missing from inventory.warehouse.', 'PostgreSQL ledsone; admin dashboard.digitweblk.com screenshots', 'validation/DB_Designer_Gap_Report_Container_Received_20260915.md', '7 gaps evidenced with counts; 12 database fixes requested (D1-D12)', TRUE, 'Prove a data gap by reconciling three independent systems row by row before proposing any code change', 'No count is reported without the SELECT that produced it', 'Supply list, receipts and container links live only in the admin system', 'Send the gap report to the database designer and track D1-D12', 'completed', 'high', TRUE, TRUE, 'gap-report,container,received-date,three-source-audit', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A06', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'implementation', 'Fill container and received date from the last arrived PO and the warehouse history', 'Rule A shows the last ARRIVED PO when the newest PO has not arrived (9 components); Rule B fills the received date from the latest warehouse stock-in even when older than the latest PO (21 components). Received coverage rose from 188 to 216 of 269, and container coverage stayed at 244. Both rules were approved by the user after the LSMS3202 and LSGLST evidence was shown.', 'PostgreSQL ledsone', 'dashboard-v2-sql/build_v2.py', 'received dates 188/268 -> 216/269; container 244/269; build RESULT PASS', FALSE, 'A stop-gap rule must be documented as replaceable, so the real source can retire it cleanly', 'Every filled value carries its source in the row notes', 'History text is a frozen partial copy (26 Aug), so it cannot see later receipts', 'Replace with the real supply tables when they exist', 'completed', 'medium', TRUE, TRUE, 'received-date,fallback,rule-a,rule-b', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

INSERT INTO daily_task.tbl_scwts_sarujanan (activity_id, activity_date, developer, project_code, project_name, requirement_id, deliverable_id, activity_type, activity_title, activity_summary, systems_touched, files_touched, evidence_refs, reusable_asset_created, reusable_pattern, validation_rule, gap_or_risk, next_action, status, priority, llm_queryable, company_knowledge_candidate, memory_tags, source_skill_file, source_type)
VALUES ('D01-A07', DATE '2026-09-15', 'sarujanan', 'scwts', 'Supplier-to-Customer Workflow Tracking System', 'REQ-03', 'D01', 'implementation', 'Start the responsive rebuild: release the fixed shell and scale every control', 'Found the cause of the poor scaling: the page is locked to 100vh with overflow hidden, so on narrow or short screens the header, filters and KPI cards consume the height and the pager becomes unreachable (measured failing at 1024, 600 and 375). Added clamp() scaling for fonts, padding, gaps, icons and images, released the fixed shell below 1024px or 700px height, turned the filter bar into a grid and let the app bar wrap so Theme and CSV stop falling off screen at 375px. Measured before/after at 8 viewports.', 'local filesystem; headless Chrome', 'dashboard-v2-sql/make_html.py', '8 viewports measured; pager reachable at every width; 1920 and 1440 pixel-identical to before', TRUE, 'Prove a CSS-only change with md5 of the file outside the style block plus a driven interaction harness', 'Payload, script and markup bytes identical before and after a CSS change', 'Fixed shell kept on desktop, so 1366x768 still shows a short table', 'Finish the validation report and publish nothing until approved', 'completed', 'high', TRUE, TRUE, 'responsive,css,clamp,shell-release', '2026-09-15__sarujanan__scwts__REQ-03-D01.md', 'skill_file')
ON CONFLICT (project_code, activity_id) DO UPDATE SET activity_date=EXCLUDED.activity_date, developer=EXCLUDED.developer, project_code=EXCLUDED.project_code, project_name=EXCLUDED.project_name, requirement_id=EXCLUDED.requirement_id, deliverable_id=EXCLUDED.deliverable_id, activity_type=EXCLUDED.activity_type, activity_title=EXCLUDED.activity_title, activity_summary=EXCLUDED.activity_summary, systems_touched=EXCLUDED.systems_touched, files_touched=EXCLUDED.files_touched, evidence_refs=EXCLUDED.evidence_refs, reusable_asset_created=EXCLUDED.reusable_asset_created, reusable_pattern=EXCLUDED.reusable_pattern, validation_rule=EXCLUDED.validation_rule, gap_or_risk=EXCLUDED.gap_or_risk, next_action=EXCLUDED.next_action, status=EXCLUDED.status, priority=EXCLUDED.priority, llm_queryable=EXCLUDED.llm_queryable, company_knowledge_candidate=EXCLUDED.company_knowledge_candidate, memory_tags=EXCLUDED.memory_tags, source_skill_file=EXCLUDED.source_skill_file, source_type=EXCLUDED.source_type, updated_at=now();

-- confirm
SELECT activity_id, activity_date, activity_type, priority, activity_title
FROM daily_task.tbl_scwts_sarujanan
WHERE project_code='scwts' AND requirement_id='REQ-03' AND deliverable_id='D01'
ORDER BY activity_id;
SELECT count(*) AS scwts_total FROM daily_task.tbl_scwts_sarujanan WHERE project_code='scwts';
