-- 2026-07-24 SCWTS daily activities -> daily_task.tbl_scwts_sarujanan
-- Idempotent: CREATE IF NOT EXISTS + upsert on (project_code, activity_id).
CREATE SCHEMA IF NOT EXISTS daily_task;

CREATE TABLE IF NOT EXISTS daily_task.tbl_scwts_sarujanan (
  activity_id                  text,
  activity_date                date,
  developer                    text DEFAULT 'sarujanan',
  project_code                 text,
  project_name                 text,
  requirement_id               text,
  deliverable_id               text,
  activity_type                text,
  activity_title               text,
  activity_summary             text,
  systems_touched              text,
  files_touched                text,
  evidence_refs                text,
  reusable_asset_created       boolean,
  reusable_pattern             text,
  validation_rule              text,
  gap_or_risk                  text,
  next_action                  text,
  status                       text DEFAULT 'completed',
  priority                     text DEFAULT 'medium',
  llm_queryable                boolean,
  company_knowledge_candidate  boolean,
  memory_tags                  text,
  source_skill_file            text,
  source_type                  text DEFAULT 'skill_file',
  created_at                   timestamptz DEFAULT now(),
  updated_at                   timestamptz DEFAULT now(),
  PRIMARY KEY (project_code, activity_id)
);

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A01',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Fix header dead band and KPI card overlap in master tracking shell',
    'The .appbar declared height:104px but as a flex item of a 100vh .main it shrank to 48px, while .filterbar stayed pinned at top:104px. This left a 56px dead band under the header and the toolbar (z-index 30) covered the top 34px of every KPI card. Fixed by making the header and toolbar non-shrinking flex items and removing the hardcoded sticky offset. Verified in headless Chrome: gap 56px->0 and card overlap 34px->0.',
    'html, css, headless chrome',
    'dashboard-v1/index.html',
    'headless chrome measurement: gap=0, overlap=0',
    FALSE,
    'Flex-shell rule: any fixed-height flex item in a viewport-locked column must set flex:0 0 auto, and sticky offsets must never hardcode a sibling''s height.',
    'Header and toolbar must not overlap KPI cards at any viewport width; measured overlap must be 0.',
    'Hardcoded sticky offsets silently break when a sibling flex item shrinks.',
    'Re-check shell layout after any change to .main height or header content.',
    'completed',
    'medium',
    TRUE,
    TRUE,
    'scwts,ui,css,flexbox,sticky,layout,regression',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A02',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Fix accessibility: unassociated form labels in filter toolbar and pagination',
    'All 9 label elements in the filter bar had no for attribute and did not wrap their control, and two were empty <label>&nbsp;</label> spacers; the rows-per-page select was labelled only by a span. Added for attributes to all 7 real labels, replaced the dummy labels with aria-hidden spacers, and converted the rows-per-page wrapper to a real label. Audited every input/select/textarea afterwards: 0 unlabelled controls, 0 dangling for references.',
    'html, accessibility',
    'dashboard-v1/index.html',
    'audit script output: unlabelled controls NONE; dangling for refs none',
    FALSE,
    'Form-control audit: enumerate every input/select/textarea and assert each resolves to a label via for= or wrapping, and that every for= points at an existing id.',
    'Zero unlabelled form controls and zero dangling for= references.',
    'Editor red-lines were accessibility warnings, not syntax errors - easy to dismiss wrongly.',
    'Run the same audit on the main dashboard/index.html.',
    'completed',
    'low',
    TRUE,
    TRUE,
    'scwts,accessibility,a11y,labels,forms,audit',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A03',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Resolve Vercel 404 by renaming the page to index.html',
    'Vercel returned 404: NOT_FOUND because dashboard-v1/ contained only supplier_basket_to_customer_home.html and no index.html, so the root URL had nothing to serve. Confirmed no script, config or doc referenced the old filename, renamed it to index.html, and verified it still renders with full data. Documented that Vercel Root Directory must be set to dashboard-v1.',
    'vercel, static hosting',
    'dashboard-v1/index.html',
    'page renders after rename: 6,997 records, pagination intact',
    FALSE,
    'Static-host rule: a deployed directory must contain index.html at its root, or configure a rewrite; URLs are case-sensitive.',
    'Deployed directory must expose index.html at its configured root.',
    'Deploy root directory setting is external to the repo and must be set in the Vercel UI.',
    'Confirm Vercel Root Directory is set to dashboard-v1.',
    'completed',
    'medium',
    TRUE,
    TRUE,
    'scwts,vercel,deployment,404,static-hosting',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A04',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'investigation',
    'Discover and validate the true product data model (inv_products, inv_product_combo)',
    'Replaced assumption-based joins with the real inventory model. Proved inv_products is the SKU master (sku UNIQUE 43,844/43,844) and that inv_product_combo maps product=COMBO id to inventory=COMPONENT id with pack_count as quantity, while product_combo is only a row PK and product=inventory marks a single. Verified with a worked example: product 5930 resolves to combo CRSF100BM+PHSH1PBRYB+SCRN70BM+LSFT220BM and its four inventory rows are exactly those four components.',
    'postgresql, mcp, psycopg2',
    'dashboard-v1-sql/build_new_scope.py',
    'FK checks: product->inv_products 120,845/120,853; inventory->inv_products 120,851/120,853; 6,354 self-maps = singles',
    TRUE,
    'Validate every join before coding: check PK uniqueness, FK resolution rate, and confirm semantics with a worked example rather than inferring from column names.',
    'product_combo must never be used as a foreign key; combo membership comes only from product/inventory with inventory <> product.',
    'Column names were misleading - product_combo looks like the combo FK but is a row PK.',
    'Add TABLE_inv_products.md and TABLE_inv_product_combo.md to the skills folder.',
    'completed',
    'high',
    TRUE,
    TRUE,
    'scwts,data-model,inv-products,inv-product-combo,joins,validation,postgres',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A05',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Replace SKU string-splitting with the authoritative combo-component mapping',
    'Components were previously derived by splitting the combo SKU on ''+''. Measured that 28,522 of 83,073 split parts (34%) match no real component and that the authoritative mapping holds 120,851 rows versus 83,073 split parts - pack-suffixed parts such as PHCHPCRYB3PK never matched the real component PHCHPCRYB. Rebuilt the component derivation entirely on inv_product_combo.',
    'postgresql, python',
    'dashboard-v1-sql/build_new_scope.py',
    '28,522/83,073 split parts unmatched; 120,851 true mapping rows',
    FALSE,
    'Never parse a composite key out of a SKU string when a mapping table exists; string encoding drifts from the relational truth.',
    'Combo components must come from inv_product_combo, never from splitting the SKU on ''+''.',
    'Any other report still splitting on ''+'' carries the same 34% error.',
    'Grep the codebase for string_to_array(sku,''+'') and migrate remaining users.',
    'completed',
    'high',
    TRUE,
    TRUE,
    'scwts,sku,combo,mapping,string-split,data-quality',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A06',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'implementation',
    'Implement SKU normalisation for country and channel suffixes',
    'Listing SKUs carry marketplace/country suffixes (_DE, -IDE, -CA, _AMN, _KR, _TH and 15 more) so they failed to match the product master. Implemented resolution as COALESCE(NULLIF(TRIM(mapped_sku),''''),TRIM(sku)) followed by stripping one trailing [_-][A-Za-z]{2,4} suffix. Resolution improved from 11,558 to 14,658 of 15,437 distinct SKUs (95%), and 30,111 of 31,132 listing rows (97%).',
    'postgresql, regex',
    'dashboard-v1-sql/build_new_scope.py',
    'direct 11,558 + via-base 3,100 = 14,658/15,437 (95%)',
    TRUE,
    'SKU resolution ladder: prefer mapped_sku, fall back to sku, then retry after stripping one country/channel suffix before declaring a SKU unresolved.',
    'Listing SKUs must be resolved through mapped_sku and suffix normalisation before joining to the product master.',
    '779 SKUs (3%) remain unresolved - absent from inv_products entirely.',
    'Decide whether the 779 unresolved SKUs are retired or need mapping.',
    'completed',
    'high',
    TRUE,
    TRUE,
    'scwts,sku,normalisation,mapped-sku,suffix,regex,resolution',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A07',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Correct listing scope: date window, is_parent, wrong_sku and empty SKUs',
    'The listing query had no created_at filter, so 12,880 of 14,977 rows (86%) predated the window, reaching back to 2019-06-26 and surfacing as wrong Listing Dates. It also used is_child=1, which silently dropped 1,183 standalone listings that all carry a real URL, price and image. Corrected the scope to created_at >= 2026-01-01 AND is_parent=0 AND wrong_sku=0 AND non-empty SKU, and confirmed is_deleted/is_ended are no-ops in-window.',
    'postgresql',
    'dashboard-v1-sql/04_listings.sql; dashboard-v1-sql/build_new_scope.py',
    '86% out-of-window rows removed; 1,183 standalone listings recovered; 181/317 parent SKUs would have double-counted',
    FALSE,
    'Sellable-listing filter: exclude parent rows (they duplicate their children), keep standalone rows, and always window on the listing creation date.',
    'Listing Date must come from listing_data.created_at and every displayed row must fall on or after the window start.',
    'is_child=1 looks correct but excludes non-variant listings.',
    'Apply the same corrected scope to sql/listings.sql used by the main dashboard.',
    'completed',
    'high',
    TRUE,
    TRUE,
    'scwts,listing-data,scope,filter,is-parent,wrong-sku,listing-date',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A08',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Stop presenting a forecast date as Container Arrival',
    'Container Arrival displayed COALESCE(expected_completion_date, finished_date, confirmed_date), so a forecast reaching 2026-08-31 rendered as a real arrival (the 04-Aug-2026 report). Verified no arrival-date column exists in supplier.containers or supplier.orders. Relabelled the column to Container Status driven by status_arrived (Arrived / In Transit) and moved the forecast into Notes. Investigation also showed the flag is stale: 395 of 497 not arrived, of which 224 are overdue.',
    'postgresql, supplier schema',
    'dashboard-v1-sql/01_components.sql; dashboard-v1/index.html',
    '0 future dates remain in the arrival field; PO TBO032026DE shipped, ETA 2026-04-26, 89 days overdue',
    FALSE,
    'Never substitute a forecast or proxy date for a factual event date; expose the status flag instead and label the forecast explicitly.',
    'No future-dated value may appear in any arrival field; forecasts must be labelled as forecasts.',
    'status_arrived is not maintained on arrival - 224 overdue POs still flagged in transit.',
    'Escalate the stale status_arrived flag to purchasing (owner Tamilchelvan).',
    'completed',
    'high',
    TRUE,
    TRUE,
    'scwts,container,arrival,forecast,status-arrived,data-quality,supplier',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A09',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'enhancement',
    'Rebuild product detail drawer as full-height one-page view with component images',
    'Redesigned the row detail drawer to fill the panel height with no scrollbar and to show one product image per component in the combo, sourced from each component''s own listing main_image_url. Components render in a fixed-height horizontal strip so a 2-part and a 7-part combo produce identical drawer height. Verified scrollHeight equals clientHeight at 1034, 900, 768, 700 and 660px, with a compact tier below 770px.',
    'html, css, javascript, headless chrome',
    'dashboard-v1/index.html',
    'no-scroll verified at 5 viewport heights; 3-part combo shows 3 images, 7-part shows 7',
    TRUE,
    'Fixed-height horizontal strip keeps a detail panel''s height constant regardless of child count, so a one-page (no-scroll) dialog stays one-page.',
    'Detail dialog must never scroll vertically: scrollHeight must equal clientHeight at every supported viewport height.',
    'Very short viewports need a compact media tier or content overflows.',
    'Reuse the component-image strip pattern on the main dashboard drawer.',
    'completed',
    'medium',
    TRUE,
    TRUE,
    'scwts,ui,drawer,dialog,component-images,no-scroll,responsive',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A10',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'bugfix',
    'Fix hover tooltip overlapping the sticky Record ID column',
    'The cell tooltip positioned itself at the cell''s raw viewport left. Because the Record ID column is position:sticky, a horizontally scrolled cell sat underneath it (measured left of -79 to -479px) and the tooltip was drawn on top of the Record ID text. Clamped the tooltip''s left to the sticky column''s right edge, applied after the right-edge clamp so it cannot be pushed back underneath. Verified tooltip left = 155 against sticky right = 147 at every scroll offset with the tooltip still visible.',
    'javascript, css, headless chrome',
    'dashboard-v1/index.html',
    'tooltip left 155 vs sticky right 147 at scrollLeft 900/1000/1100/1300; overlap false',
    FALSE,
    'When a table has a sticky column, any absolutely positioned overlay derived from cell coordinates must be clamped to that column''s edge.',
    'Overlays must never render underneath or on top of a sticky column; measured overlap must be 0.',
    'Raw getBoundingClientRect values are misleading inside horizontally scrolled sticky tables.',
    'Audit other overlays (drawer, chips) for the same sticky-column assumption.',
    'completed',
    'medium',
    TRUE,
    TRUE,
    'scwts,ui,tooltip,sticky-column,overlay,positioning',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A11',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'implementation',
    'Publish master tracking dashboard to the Varman AIOS Hub',
    'Published the self-contained page to the Varman AIOS Hub by upserting into varman_aios.hub_pages via push_to_hub.js as member_name sarujanan with slug supplier-to-customer-workflow-tracking. Verified prerequisites first: Node v22, pg installed, no external script/link references, and the UNIQUE (member_name, page_slug) constraint that makes the upsert update in place. Confirmed the stored payload byte-for-byte against the file on disk.',
    'postgresql, node, varman aios hub',
    'dashboard-v1-update/push_to_hub.js',
    'hub row id 14; octet_length = 1,011,327 bytes = file size; content ends </html>',
    TRUE,
    'Publish-and-verify: after an upsert of a document, compare octet_length against the source file size and check the trailing bytes, because length() counts characters and under-reports on multi-byte content.',
    'Published HTML must be fully self-contained and its stored byte length must equal the source file size.',
    'The hub credential can reach the whole database, so it must only ever touch varman_aios.hub_pages for the member''s own rows.',
    'Re-push after each data rebuild so the hub stays in sync.',
    'completed',
    'medium',
    TRUE,
    TRUE,
    'scwts,hub,varman-aios,publish,upsert,verification',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();

INSERT INTO daily_task.tbl_scwts_sarujanan (
    activity_id,
    activity_date,
    developer,
    project_code,
    project_name,
    requirement_id,
    deliverable_id,
    activity_type,
    activity_title,
    activity_summary,
    systems_touched,
    files_touched,
    evidence_refs,
    reusable_asset_created,
    reusable_pattern,
    validation_rule,
    gap_or_risk,
    next_action,
    status,
    priority,
    llm_queryable,
    company_knowledge_candidate,
    memory_tags,
    source_skill_file,
    source_type
) VALUES (
    'D03-A12',
    DATE '2026-07-24',
    'sarujanan',
    'scwts',
    'Supplier-to-Customer Workflow Tracking System',
    'REQ-01',
    'D03',
    'implementation',
    'Rebuild dashboard data on the NEW-product scope with full reconciliation',
    'Rebuilt the entire data-generation layer as build_new_scope.py using the validated model, with the UI left byte-identical apart from the embedded payload. Scope agreed with the manager: only products whose inv_products.created_at >= 2026-01-01 and isdeleted=0, listed on or after 2026-01-01, one row per Combo SKU per marketplace. Result reconciles exactly with PostgreSQL: 2,852 rows, 1,542 combos, 826 components, 103 new components, 3,179 units, GBP 67,733.17, 2,318 orders. Also repaired a filter interaction in data only: 2,031 rows carried a pre-2026 supplier receipt and rowDate (crecv||ldate||ccreate) hid them, leaving just 821 visible; pre-window receipts were moved to Notes so every row anchors to its in-window Listing Date.',
    'postgresql, python, psycopg2, mcp',
    'dashboard-v1-sql/build_new_scope.py; dashboard-v1/index.html; dashboard-v1-sql/supplier_meta.psv',
    'PG vs dashboard identical on 8 metrics; UI diff confirms HTML/CSS/JS unchanged; 2,852/2,852 rows visible under default filter',
    TRUE,
    'Two-phase build: derive everything reachable from the public schema locally, fetch privileged attributes separately via MCP into a cached file, then merge - keeps the pipeline runnable under a restricted role.',
    'Generated data must reconcile with PostgreSQL on row count, combos, components, units, revenue and orders before publishing, and the UI must remain byte-identical apart from the payload.',
    'Sales on marketplaces without an in-window listing (GBP 17,780.66) are excluded by the row grain; 779 SKUs remain unresolved.',
    'Wire build_new_scope.py into the 10:00 daily refresh job.',
    'completed',
    'high',
    TRUE,
    TRUE,
    'scwts,rebuild,new-scope,inv-products,reconciliation,validation,payload',
    '2026-07-24__sarujanan__scwts__REQ-01-D03.md',
    'skill_file'
)
ON CONFLICT (project_code, activity_id) DO UPDATE SET
      activity_date = EXCLUDED.activity_date,
      developer = EXCLUDED.developer,
      project_name = EXCLUDED.project_name,
      requirement_id = EXCLUDED.requirement_id,
      deliverable_id = EXCLUDED.deliverable_id,
      activity_type = EXCLUDED.activity_type,
      activity_title = EXCLUDED.activity_title,
      activity_summary = EXCLUDED.activity_summary,
      systems_touched = EXCLUDED.systems_touched,
      files_touched = EXCLUDED.files_touched,
      evidence_refs = EXCLUDED.evidence_refs,
      reusable_asset_created = EXCLUDED.reusable_asset_created,
      reusable_pattern = EXCLUDED.reusable_pattern,
      validation_rule = EXCLUDED.validation_rule,
      gap_or_risk = EXCLUDED.gap_or_risk,
      next_action = EXCLUDED.next_action,
      status = EXCLUDED.status,
      priority = EXCLUDED.priority,
      llm_queryable = EXCLUDED.llm_queryable,
      company_knowledge_candidate = EXCLUDED.company_knowledge_candidate,
      memory_tags = EXCLUDED.memory_tags,
      source_skill_file = EXCLUDED.source_skill_file,
      source_type = EXCLUDED.source_type,
      updated_at = now();
